# Generated by Django 3.2.12 on 2022-03-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, null=True, verbose_name='Текст')),
                ('clue', models.CharField(max_length=50, null=True, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='ID телеграмма')),
                ('user', models.CharField(max_length=500, null=True, verbose_name='Пользователь')),
                ('role', models.CharField(max_length=12, null=True, verbose_name='Роль')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Город')),
                ('experience', models.CharField(max_length=12, null=True, verbose_name='Опыт работы')),
                ('speciality', models.CharField(max_length=50, null=True, verbose_name='Специализация')),
                ('photo_url', models.CharField(max_length=500, null=True, verbose_name='Фото')),
                ('portfolio_url', models.CharField(max_length=500, null=True, verbose_name='Портфолио')),
                ('description', models.CharField(max_length=1000, null=True, verbose_name='О себе')),
                ('registration_date', models.DateTimeField(null=True, verbose_name='Дата регистрации')),
                ('msg_id', models.CharField(max_length=1000, null=True, verbose_name='ID сообщения')),
                ('mode', models.CharField(max_length=50, null=True, verbose_name='Процесс')),
                ('step', models.IntegerField(null=True, verbose_name='Шаг')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='ID телеграмма')),
                ('msg_id', models.IntegerField(verbose_name='ID сообщения')),
                ('text', models.CharField(max_length=500, null=True, verbose_name='Текст')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата публикации')),
                ('city', models.CharField(max_length=500, null=True, verbose_name='Город для публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
